version: '3.3'  # 使用支持的版本

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ywy20010917.
      MYSQL_DATABASE: bitcoin_explorer
      MYSQL_USER: zerzerr917
      MYSQL_PASSWORD: Ywy20010917.
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - bitcoin-explorer_default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "3030:3030"
    environment:
      DATABASE_URL: mysql://zerzerr917:Ywy20010917.@mysql/bitcoin_explorer
    networks:
      - bitcoin-explorer_default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - bitcoin-explorer_default

volumes:
  mysql-data: {}

networks:
  bitcoin-explorer_default:
    external: true  # 使用外部网络
